security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            id: App\Security\UserProvider
#            entity:
#                class: App\Entity\User
#                property: pseudo,email

    firewalls:
        main:
            user_checker: App\Security\UserChecker
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 900     # un quart d'heure (secondes)
                path: /
                name: REMEMBERME  # Nom du cookie
    access_control:
            - { path: ^/login, roles: PUBLIC_ACCESS }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/, roles: ROLE_USER }
